services:
  - type: web
    name: skill-improvement-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        fromService:
          type: secret
          name: openai_api_key
      - key: YOUTUBE_API_KEY
        fromService:
          type: secret
          name: youtube_api_key
    plan: free
